export const EXPECT_LIVE_VIEW_URL_ENV_NAME = "EXPECT_LIVE_VIEW_URL";
export const EXPECT_REPLAY_OUTPUT_ENV_NAME = "EXPECT_REPLAY_OUTPUT_PATH";
export const EXPECT_COOKIE_BROWSERS_ENV_NAME = "EXPECT_COOKIE_BROWSERS";
export const EXPECT_CDP_URL_ENV_NAME = "EXPECT_CDP_URL";
export const LIVE_VIEW_PAGE_POLL_INTERVAL_MS = 500;
export const DUPLICATE_REQUEST_WINDOW_MS = 500;
