export const BROWSER_TESTER_VIDEO_OUTPUT_ENV_NAME = "BROWSER_TESTER_VIDEO_OUTPUT_PATH";
export const BROWSER_TESTER_LIVE_VIEW_URL_ENV_NAME = "BROWSER_TESTER_LIVE_VIEW_URL";
export const LIVE_VIEW_SCREENCAST_QUALITY = 40;
export const LIVE_VIEW_SCREENCAST_MAX_WIDTH_PX = 960;
export const LIVE_VIEW_SCREENCAST_MAX_HEIGHT_PX = 540;
export const LIVE_VIEW_SCREENCAST_EVERY_NTH_FRAME = 2;
export const LIVE_VIEW_PAGE_POLL_INTERVAL_MS = 500;
export const LIVE_VIEW_MJPEG_BOUNDARY = "frame";
