export const BROWSER_TESTER_LIVE_VIEW_URL_ENV_NAME = "BROWSER_TESTER_LIVE_VIEW_URL";
export const BROWSER_TESTER_REPLAY_OUTPUT_ENV_NAME = "BROWSER_TESTER_REPLAY_OUTPUT_PATH";
export const LIVE_VIEW_PAGE_POLL_INTERVAL_MS = 500;
