export { StdioTransport } from "./transport.js";
export {
  AcpAgentConfig,
  KNOWN_ACP_AGENTS,
  connectAcpAgent,
  type AcpClientConnection,
  type SessionUpdateEvent,
} from "./acp-client.js";

export {
  AcpClientError,
  JsonRpcParseError,
  SessionNotFoundError,
  TransportClosedError,
} from "./errors.js";

export {
  PROTOCOL_VERSION,
  JSON_RPC_VERSION,
  ERROR_CODE_PARSE,
  ERROR_CODE_INVALID_REQUEST,
  ERROR_CODE_METHOD_NOT_FOUND,
  ERROR_CODE_INVALID_PARAMS,
  ERROR_CODE_INTERNAL,
  ERROR_CODE_AUTH_REQUIRED,
  ERROR_CODE_NOT_FOUND,
} from "./constants.js";

export {
  SessionId,
  ProtocolVersion,
  RequestId,
  Implementation,
  ClientCapabilities,
  AgentCapabilities,
  PromptCapabilities,
  McpCapabilities,
  EnvVariable,
  McpServer,
  InitializeRequest,
  InitializeResponse,
  AuthenticateRequest,
  AuthenticateResponse,
  NewSessionRequest,
  NewSessionResponse,
  SessionMode,
  SessionModeState,
  LoadSessionRequest,
  LoadSessionResponse,
  ContentBlock,
  PromptRequest,
  StopReason,
  PromptResponse,
  CancelNotification,
  ToolKind,
  ToolCallStatus,
  PlanEntry,
  SessionUpdate,
  SessionNotification,
  SetSessionModeRequest,
  SetSessionModeResponse,
  PermissionOption,
  RequestPermissionRequest,
  RequestPermissionOutcome,
  RequestPermissionResponse,
} from "./schemas.js";
