export { StdioTransport } from "./transport.js";
export {
  AcpAgentConfig,
  KNOWN_ACP_AGENTS,
  connectAcpAgent,
  type AcpClientConnection,
  type ConnectOptions,
  type PermissionHandler,
  type PermissionRequest,
  type SessionUpdateEvent,
} from "./acp-client.js";

export { AcpClientError, JsonRpcParseError, TransportClosedError } from "./errors.js";

export {
  PROTOCOL_VERSION,
  JSON_RPC_VERSION,
  REQUEST_TIMEOUT_MS,
  ERROR_CODE_PARSE,
  ERROR_CODE_INVALID_REQUEST,
  ERROR_CODE_METHOD_NOT_FOUND,
  ERROR_CODE_INVALID_PARAMS,
  ERROR_CODE_INTERNAL,
  ERROR_CODE_AUTH_REQUIRED,
  ERROR_CODE_NOT_FOUND,
} from "./constants.js";

export {
  SessionId,
  ToolCallId,
  TerminalId,
  ProtocolVersion,
  RequestId,
  Implementation,
  FileSystemCapabilities,
  ClientCapabilities,
  AgentCapabilities,
  PromptCapabilities,
  McpCapabilities,
  SessionCapabilities,
  EnvVariable,
  McpServer,
  McpServerStdio,
  McpServerHttp,
  McpServerSse,
  InitializeRequest,
  InitializeResponse,
  AuthenticateRequest,
  AuthenticateResponse,
  NewSessionRequest,
  NewSessionResponse,
  SessionMode,
  SessionModeState,
  LoadSessionRequest,
  LoadSessionResponse,
  TextContent,
  ImageContent,
  ResourceLink,
  EmbeddedResource,
  ContentBlock,
  PromptRequest,
  StopReason,
  PromptResponse,
  CancelNotification,
  ToolKind,
  ToolCallStatus,
  ToolCallLocation,
  ToolCallContentItem,
  PlanEntryPriority,
  PlanEntryStatus,
  PlanEntry,
  SessionUpdate,
  SessionNotification,
  SetSessionModeRequest,
  SetSessionModeResponse,
  PermissionOptionKind,
  PermissionOption,
  RequestPermissionRequest,
  RequestPermissionOutcome,
  RequestPermissionResponse,
  ReadTextFileRequest,
  ReadTextFileResponse,
  WriteTextFileRequest,
  WriteTextFileResponse,
} from "./schemas.js";
